### ISSUE TITLE
Invalid argument error when step definition regex has an argument with whitespace.

### ISSUE THREAD

**Issue by tzehon** [SquirrelGrip/cucumber-parallel#1]
Running the step below will cause the program to error out.
@Step("^to eat some 'big red apples'$")
public void eatApples(String appleDescription) {
    // Do something
}

The interim fix is to use a capture group (.*) or to use a string argument without spaces, e.g. "big_red_apples"

**Comment by SquirrelGrip** [comment]
Yes that is right...you are required to enter a capture group, preferably something like (.*) or (.+)

The quote is not part of the regular expression capturing group.

So given the example.
@Step("^to eat some '(.*)'$")
public void eatApples(String appleDescription) {
// Do something
}

should work with the capture being 'big red apples' without the quotes. The quotes are there just to make the matching easier as sometimes the regex parser does not know where to end the capturing.
